// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entity.Entities.Firma", b =>
                {
                    b.Property<int>("FirmaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FirmaID"), 1L, 1);

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Onay")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("SatısBaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("SatısBitisSaati")
                        .HasColumnType("time");

                    b.HasKey("FirmaID");

                    b.ToTable("Firmalar");
                });

            modelBuilder.Entity("Entity.Entities.Siparis", b =>
                {
                    b.Property<int>("SiparisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisID"), 1L, 1);

                    b.Property<int?>("FirmaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SiparisSaati")
                        .HasColumnType("datetime2");

                    b.Property<string>("SiparisVeren")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("SiparisID");

                    b.HasIndex("FirmaID");

                    b.HasIndex("UrunID");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("Entity.Entities.Urun", b =>
                {
                    b.Property<int>("UrunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunID"), 1L, 1);

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<short>("Stok")
                        .HasColumnType("smallint");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UrunID");

                    b.HasIndex("FirmaID");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("Entity.Entities.Siparis", b =>
                {
                    b.HasOne("Entity.Entities.Firma", "Firma")
                        .WithMany("Siparis")
                        .HasForeignKey("FirmaID");

                    b.HasOne("Entity.Entities.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Entity.Entities.Urun", b =>
                {
                    b.HasOne("Entity.Entities.Firma", "Firma")
                        .WithMany("Uruns")
                        .HasForeignKey("FirmaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("Entity.Entities.Firma", b =>
                {
                    b.Navigation("Siparis");

                    b.Navigation("Uruns");
                });
#pragma warning restore 612, 618
        }
    }
}
